# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditInterfaceJuniper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import ipaddress
from PyQt5 import QtCore, QtGui, QtWidgets
from netaddr import IPAddress

from Error import Ui_Error


class Ui_EditInterfacesJuniper:
    firewall = None
    data = []
    interface = None
    interface_name = None
    MainWindow = None
    PrevWindow = None

    def reload(self):
        try:
            _translate = QtCore.QCoreApplication.translate
            self.interface_name = "ge-0/0/"+str(self.interface)
            self.IpEdit.setText(_translate("MainWindow", self.data[1]))
            self.MaskEdit.setText(_translate("MainWindow", self.data[2]))
        except Exception as e:
            self.openErrorWindow(e)

    def commit(self):
        try:
            if self.data[1] == self.IpEdit.text() and self.data[2] == self.MaskEdit.text():
                self.openErrorWindow("Data not changed")
                self.exit()
            else:
                if self.data[0][0] != "0":
                    self.firewall.load_merge_candidate(
                        config="set interfaces " + str(self.interface_name) + " vlan-tagging unit " + str(self.data[0])
                               + " vlan-id " + str(self.data[0]) + " family inet address " + self.IpEdit.text() + "/"
                               + str(IPAddress(self.MaskEdit.text()).netmask_bits()))
                if self.data[0][0] == "0":
                    if self.valid():
                        self.firewall.load_merge_candidate(
                            config="delete interfaces " + str(self.interface_name)+"\nset interfaces " + str(self.interface_name)
                                    + " unit 0 family inet address " + self.IpEdit.text() + "/" + str(IPAddress(self.MaskEdit.text()).netmask_bits()))
                self.firewall.commit_config()
                self.exit()
        except Exception as e:
            self.openErrorWindow(e)

    def valid(self):
        try:
            IPAddress(self.MaskEdit.text()).netmask_bits()
            ipaddress.ip_address(self.IpEdit.text())
            return True
        except Exception as e:
            self.openErrorWindow(e)
            return False

    def exit(self):
        self.PrevWindow.show()
        self.centralwidget.window().close()

    def openErrorWindow(self, txt):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Error()
        self.ui.setupUi(self.window, self.MainWindow)
        self.ui.reload(txt)
        self.window.show()

    def setupUi(self, MainWindow, PrevWindow):
        self.PrevWindow = PrevWindow
        self.PrevWindow.hide()
        self.MainWindow = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(389, 218)
        MainWindow.setMinimumSize(QtCore.QSize(389, 218))
        MainWindow.setMaximumSize(QtCore.QSize(389, 218))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 121, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.CommitIntEdit = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.commit())
        self.CommitIntEdit.setGeometry(QtCore.QRect(250, 130, 75, 23))
        self.CommitIntEdit.setObjectName("CommitIntEdit")

        self.MaskEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MaskEdit.setGeometry(QtCore.QRect(210, 70, 131, 20))
        self.MaskEdit.setObjectName("MaskEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 110, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.IpEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.IpEdit.setGeometry(QtCore.QRect(210, 40, 131, 20))
        self.IpEdit.setObjectName("IpEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyNet"))
        self.label_2.setText(_translate("MainWindow", "Subnet Mask"))
        self.CommitIntEdit.setText(_translate("MainWindow", "Commit"))
        self.label.setText(_translate("MainWindow", "IP Address"))



