# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Error:
    MainWindow = None
    PrevWindow = None

    def reload(self, txt):
        _translate = QtCore.QCoreApplication.translate
        self.errorLabel.setText(_translate("MainWindow", str(txt)))

    def exit(self):
        self.centralwidget.window().close()

    def setupUi(self, MainWindow, PrevWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 130)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 130))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 130))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.exit())
        self.backBtn.setGeometry(QtCore.QRect(445, 90, 75, 23))
        self.backBtn.setObjectName("backBtn")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(10, 30, 980, 31))
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyNet"))
        self.backBtn.setText(_translate("MainWindow", "Back"))
        self.errorLabel.setText(_translate("MainWindow", "TextLabel"))

