# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


from EditInterfaces import Ui_EditInterfaces
from Error import Ui_Error


def cidr_to_netmask(netmask):
    cidr = int(netmask)
    mask = (0xffffffff >> (32 - cidr)) << (32 - cidr)

    res = (str((0xff000000 & mask) >> 24) + '.' +
           str((0x00ff0000 & mask) >> 16) + '.' +
           str((0x0000ff00 & mask) >> 8) + '.' +
           str((0x000000ff & mask)))
    return res


class Ui_Interfaces():

    router = None
    intIP = []
    intMASK = []
    intList = []
    intName = []
    data = []
    is_up = []
    is_connect = []
    PrevWindow = None

    def reload(self):
        _translate = QtCore.QCoreApplication.translate
        try:
            for i in range (1, 4):
                self.is_up[i].setText(_translate("Interfaces", "OFF"))
                self.is_connect[i].setText(_translate("Interfaces", "OFF"))

            device_interfaces = self.router.get_interfaces()
            self.data.clear()
            for interface in device_interfaces:
                if device_interfaces[interface]:
                    try:
                        up = device_interfaces[interface]['is_up']
                        enable = device_interfaces[interface]['is_enabled']
                        ip_address = list(self.router.get_interfaces_ip()[interface]['ipv4'].keys())[0]
                        mask = self.router.get_interfaces_ip()[interface]['ipv4'][ip_address]['prefix_length']
                        self.intName[int(interface[-1])-1].setText(_translate("Interfaces", interface))
                        self.intIP[int(interface[-1])-1].setText(_translate("Interfaces", ip_address))
                        self.intMASK[int(interface[-1])-1].setText(_translate("Interfaces", cidr_to_netmask(mask)))
                        if up:
                            self.is_up[int(interface[-1])-1].setText(_translate("Interfaces", "ON"))
                        else:
                            self.is_up[int(interface[-1]) - 1].setText(_translate("Interfaces", "OFF"))
                        if enable:
                            self.is_connect[int(interface[-1]) - 1].setText(_translate("Interfaces", "ON"))
                        else:
                            self.is_connect[int(interface[-1]) - 1].setText(_translate("Interfaces", "OFF"))

                        self.data.append([interface[-1],
                                          ip_address,
                                          cidr_to_netmask(mask),
                                          enable])
                    except Exception as e:
                        self.intName[int(interface[-1]) - 1].setText(_translate("Interfaces", interface))
        except Exception as e:
            self.openErrorWindow(e)

    def openEditInterfacesWindow(self, intNumber):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_EditInterfaces()
        self.ui.data = self.data
        self.ui.router = self.router
        self.ui.interface = intNumber
        self.ui.setupUi(self.window, self.Interfaces)
        self.ui.reload()
        self.window.show()

    def exit(self):
        self.PrevWindow.show()
        self.centralwidget.window().close()

    def openErrorWindow(self, txt):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Error()
        self.ui.setupUi(self.window, self.Interfaces)
        self.ui.reload(txt)
        self.window.show()

    def setupUi(self, Interfaces, PrevWindow):
        self.PrevWindow = PrevWindow
        self.PrevWindow.hide()
        self.Interfaces = Interfaces

        Interfaces.setObjectName("Interfaces")
        Interfaces.resize(1000, 720)
        Interfaces.setMinimumSize(QtCore.QSize(1000, 720))
        Interfaces.setMaximumSize(QtCore.QSize(1000, 720))

        self.centralwidget = QtWidgets.QWidget(Interfaces)
        self.centralwidget.setObjectName("centralwidget")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.InterfaceName1 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName1.setGeometry(QtCore.QRect(20, 20, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName1.sizePolicy().hasHeightForWidth())
        self.InterfaceName1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName1.setFont(font)
        self.InterfaceName1.setObjectName("InterfaceName1")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.is_up_1 = QtWidgets.QLabel(self.centralwidget)
        self.is_up_1.setGeometry(QtCore.QRect(40, 110, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_up_1.sizePolicy().hasHeightForWidth())
        self.is_up_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_1.setFont(font)
        self.is_up_1.setObjectName("is_up_1")

        self.is_connect_1 = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_1.setGeometry(QtCore.QRect(40, 140, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_connect_1.sizePolicy().hasHeightForWidth())
        self.is_connect_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_1.setFont(font)
        self.is_connect_1.setObjectName("is_connect_1")

        self.InterfaceName2 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName2.setGeometry(QtCore.QRect(20, 180, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName2.sizePolicy().hasHeightForWidth())
        self.InterfaceName2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName2.setFont(font)
        self.InterfaceName2.setObjectName("InterfaceName2")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 210, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.is_up_2 = QtWidgets.QLabel(self.centralwidget)
        self.is_up_2.setGeometry(QtCore.QRect(40, 270, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_up_2.sizePolicy().hasHeightForWidth())
        self.is_up_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_2.setFont(font)
        self.is_up_2.setObjectName("is_up_2")

        self.is_connect_2 = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_2.setGeometry(QtCore.QRect(40, 300, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_connect_2.sizePolicy().hasHeightForWidth())
        self.is_connect_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_2.setFont(font)
        self.is_connect_2.setObjectName("is_connect_2")

        self.InterfaceName3 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName3.setGeometry(QtCore.QRect(20, 340, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName3.sizePolicy().hasHeightForWidth())
        self.InterfaceName3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName3.setFont(font)
        self.InterfaceName3.setObjectName("InterfaceName3")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 370, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 400, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.is_up_3 = QtWidgets.QLabel(self.centralwidget)
        self.is_up_3.setGeometry(QtCore.QRect(40, 430, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_up_3.sizePolicy().hasHeightForWidth())
        self.is_up_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_3.setFont(font)
        self.is_up_3.setObjectName("is_up_3")

        self.is_connect_3 = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_3.setGeometry(QtCore.QRect(40, 460, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_connect_3.sizePolicy().hasHeightForWidth())
        self.is_connect_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_3.setFont(font)
        self.is_connect_3.setObjectName("is_connect_3")

        self.InterfaceName4 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName4.setGeometry(QtCore.QRect(20, 500, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName4.sizePolicy().hasHeightForWidth())
        self.InterfaceName4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName4.setFont(font)
        self.InterfaceName4.setObjectName("InterfaceName4")

        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 530, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 560, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.is_up_4 = QtWidgets.QLabel(self.centralwidget)
        self.is_up_4.setGeometry(QtCore.QRect(40, 590, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_up_4.sizePolicy().hasHeightForWidth())
        self.is_up_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_4.setFont(font)
        self.is_up_4.setObjectName("is_up_4")

        self.is_connect_4 = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_4.setGeometry(QtCore.QRect(40, 620, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_connect_4.sizePolicy().hasHeightForWidth())
        self.is_connect_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_4.setFont(font)
        self.is_connect_4.setObjectName("is_connect_4")

        self.InterfaceName5 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName5.setGeometry(QtCore.QRect(470, 20, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName5.sizePolicy().hasHeightForWidth())
        self.InterfaceName5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName5.setFont(font)
        self.InterfaceName5.setObjectName("InterfaceName5")

        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(490, 50, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(490, 80, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.InterfaceName6 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName6.setGeometry(QtCore.QRect(470, 180, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName6.sizePolicy().hasHeightForWidth())
        self.InterfaceName6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName6.setFont(font)
        self.InterfaceName6.setObjectName("InterfaceName6")

        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(490, 210, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")

        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(490, 240, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")

        self.InterfaceName7 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName7.setGeometry(QtCore.QRect(470, 340, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName7.sizePolicy().hasHeightForWidth())
        self.InterfaceName7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName7.setFont(font)
        self.InterfaceName7.setObjectName("InterfaceName7")

        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(490, 370, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")

        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(490, 400, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")

        self.InterfaceName8 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceName8.setGeometry(QtCore.QRect(470, 500, 150, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfaceName8.sizePolicy().hasHeightForWidth())
        self.InterfaceName8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceName8.setFont(font)
        self.InterfaceName8.setObjectName("InterfaceName8")

        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(490, 530, 78, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")

        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(490, 560, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")

        self.InterfaceMask0 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask0.setGeometry(QtCore.QRect(190, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask0.setFont(font)
        self.InterfaceMask0.setObjectName("InterfaceMask0")

        self.InterfaceIP0 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP0.setGeometry(QtCore.QRect(190, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP0.setFont(font)
        self.InterfaceIP0.setObjectName("InterfaceIP0")

        self.InterfaceMask1 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask1.setGeometry(QtCore.QRect(190, 240, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask1.setFont(font)
        self.InterfaceMask1.setObjectName("InterfaceMask1")

        self.InterfaceIP1 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP1.setGeometry(QtCore.QRect(190, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP1.setFont(font)
        self.InterfaceIP1.setObjectName("InterfaceIP1")

        self.InterfaceIP2 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP2.setGeometry(QtCore.QRect(190, 370, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP2.setFont(font)
        self.InterfaceIP2.setObjectName("InterfaceIP2")

        self.InterfaceMask2 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask2.setGeometry(QtCore.QRect(190, 400, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask2.setFont(font)
        self.InterfaceMask2.setObjectName("InterfaceMask2")

        self.InterfaceIP3 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP3.setGeometry(QtCore.QRect(190, 530, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP3.setFont(font)
        self.InterfaceIP3.setObjectName("InterfaceIP3")

        self.InterfaceMask3 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask3.setGeometry(QtCore.QRect(190, 560, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask3.setFont(font)
        self.InterfaceMask3.setObjectName("InterfaceMask3")

        self.InterfaceIP4 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP4.setGeometry(QtCore.QRect(640, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP4.setFont(font)
        self.InterfaceIP4.setObjectName("InterfaceIP4")

        self.InterfaceMask4 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask4.setGeometry(QtCore.QRect(640, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask4.setFont(font)
        self.InterfaceMask4.setObjectName("InterfaceMask4")

        self.InterfaceIP5 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP5.setGeometry(QtCore.QRect(640, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP5.setFont(font)
        self.InterfaceIP5.setObjectName("InterfaceIP5")

        self.InterfaceMask5 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask5.setGeometry(QtCore.QRect(640, 240, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask5.setFont(font)
        self.InterfaceMask5.setObjectName("InterfaceMask5")

        self.InterfaceIP6 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP6.setGeometry(QtCore.QRect(640, 370, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP6.setFont(font)
        self.InterfaceIP6.setObjectName("InterfaceIP6")

        self.InterfaceMask6 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask6.setGeometry(QtCore.QRect(640, 400, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask6.setFont(font)
        self.InterfaceMask6.setObjectName("InterfaceMask6")

        self.InterfaceIP7 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceIP7.setGeometry(QtCore.QRect(640, 530, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceIP7.setFont(font)
        self.InterfaceIP7.setObjectName("InterfaceIP7")

        self.InterfaceMask7 = QtWidgets.QLabel(self.centralwidget)
        self.InterfaceMask7.setGeometry(QtCore.QRect(640, 560, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InterfaceMask7.setFont(font)
        self.InterfaceMask7.setObjectName("InterfaceMask7")


        self.is_up_1_data = QtWidgets.QLabel(self.centralwidget)
        self.is_up_1_data.setGeometry(QtCore.QRect(190, 110, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_1_data.setFont(font)
        self.is_up_1_data.setObjectName("is_up_1_data")

        self.is_up_2_data = QtWidgets.QLabel(self.centralwidget)
        self.is_up_2_data.setGeometry(QtCore.QRect(190, 270, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_2_data.setFont(font)
        self.is_up_2_data.setObjectName("is_up_2_data")

        self.is_up_3_data = QtWidgets.QLabel(self.centralwidget)
        self.is_up_3_data.setGeometry(QtCore.QRect(190, 430, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_3_data.setFont(font)
        self.is_up_3_data.setObjectName("is_up_3_data")

        self.is_up_4_data = QtWidgets.QLabel(self.centralwidget)
        self.is_up_4_data.setGeometry(QtCore.QRect(190, 590, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_up_4_data.setFont(font)
        self.is_up_4_data.setObjectName("is_up_4_data")

        self.is_connect_1_data = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_1_data.setGeometry(QtCore.QRect(190, 140, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_1_data.setFont(font)
        self.is_connect_1_data.setObjectName("is_connect_1_data")

        self.is_connect_2_data = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_2_data.setGeometry(QtCore.QRect(190, 300, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_2_data.setFont(font)
        self.is_connect_2_data.setObjectName("is_connect_2_data")

        self.is_connect_3_data = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_3_data.setGeometry(QtCore.QRect(190, 460, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_3_data.setFont(font)
        self.is_connect_3_data.setObjectName("is_connect__data")

        self.is_connect_4_data = QtWidgets.QLabel(self.centralwidget)
        self.is_connect_4_data.setGeometry(QtCore.QRect(190, 620, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.is_connect_4_data.setFont(font)
        self.is_connect_4_data.setObjectName("is_connect_4_data")



        self.IntEdit0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('1'))
        self.IntEdit0.setGeometry(QtCore.QRect(350, 70, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit0.setFont(font)
        self.IntEdit0.setObjectName("IntEdit0")
        self.IntEdit0.setEnabled(False)

        self.IntEdit1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('2'))
        self.IntEdit1.setGeometry(QtCore.QRect(350, 230, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit1.setFont(font)
        self.IntEdit1.setObjectName("IntEdit1")

        self.IntEdit2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('3'))
        self.IntEdit2.setGeometry(QtCore.QRect(350, 390, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit2.setFont(font)
        self.IntEdit2.setObjectName("IntEdit2")

        self.IntEdit3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('4'))
        self.IntEdit3.setGeometry(QtCore.QRect(350, 550, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit3.setFont(font)
        self.IntEdit3.setObjectName("IntEdit3")

        self.IntEdit4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('5'))
        self.IntEdit4.setGeometry(QtCore.QRect(800, 70, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit4.setFont(font)
        self.IntEdit4.setObjectName("IntEdit4")

        self.IntEdit5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('6'))
        self.IntEdit5.setGeometry(QtCore.QRect(800, 230, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit5.setFont(font)
        self.IntEdit5.setObjectName("IntEdit5")

        self.IntEdit6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('7'))
        self.IntEdit6.setGeometry(QtCore.QRect(800, 390, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit6.setFont(font)
        self.IntEdit6.setObjectName("IntEdit6")

        self.IntEdit7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.openEditInterfacesWindow('8'))
        self.IntEdit7.setGeometry(QtCore.QRect(800, 550, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntEdit7.setFont(font)
        self.IntEdit7.setObjectName("IntEdit7")

        self.IntExit = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.exit())
        self.IntExit.setGeometry(QtCore.QRect(830, 650, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IntExit.setFont(font)
        self.IntExit.setObjectName("IntExit")

        self.reloadButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.reload())
        self.reloadButton.setGeometry(QtCore.QRect(700, 650, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reloadButton.setFont(font)
        self.reloadButton.setObjectName("reloadButton")

        Interfaces.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interfaces)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")

        Interfaces.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Interfaces)
        self.statusbar.setObjectName("statusbar")
        Interfaces.setStatusBar(self.statusbar)

        self.intIP.clear()
        # append IP label to list
        self.intIP.append(self.InterfaceIP0)
        self.intIP.append(self.InterfaceIP1)
        self.intIP.append(self.InterfaceIP2)
        self.intIP.append(self.InterfaceIP3)
        self.intIP.append(self.InterfaceIP4)
        self.intIP.append(self.InterfaceIP5)
        self.intIP.append(self.InterfaceIP6)
        self.intIP.append(self.InterfaceIP7)

        self.intMASK.clear()
        # append netmask label to list
        self.intMASK.append(self.InterfaceMask0)
        self.intMASK.append(self.InterfaceMask1)
        self.intMASK.append(self.InterfaceMask2)
        self.intMASK.append(self.InterfaceMask3)
        self.intMASK.append(self.InterfaceMask4)
        self.intMASK.append(self.InterfaceMask5)
        self.intMASK.append(self.InterfaceMask6)
        self.intMASK.append(self.InterfaceMask7)

        self.intName.clear()
        self.intName.append(self.InterfaceName1)
        self.intName.append(self.InterfaceName2)
        self.intName.append(self.InterfaceName3)
        self.intName.append(self.InterfaceName4)
        self.intName.append(self.InterfaceName5)
        self.intName.append(self.InterfaceName6)
        self.intName.append(self.InterfaceName7)
        self.intName.append(self.InterfaceName8)

        self.is_up.clear()
        self.is_up.append(self.is_up_1_data)
        self.is_up.append(self.is_up_2_data)
        self.is_up.append(self.is_up_3_data)
        self.is_up.append(self.is_up_4_data)

        self.is_connect.clear()
        self.is_connect.append(self.is_connect_1_data)
        self.is_connect.append(self.is_connect_2_data)
        self.is_connect.append(self.is_connect_3_data)
        self.is_connect.append(self.is_connect_4_data)

        self.retranslateUi(Interfaces)

        QtCore.QMetaObject.connectSlotsByName(Interfaces)

    def retranslateUi(self, Interfaces):
        _translate = QtCore.QCoreApplication.translate
        Interfaces.setWindowTitle(_translate("Interfaces", "PyNet"))
        self.label_2.setText(_translate("Interfaces", "IP"))
        self.is_up_1.setText(_translate("Interfaces", "Is UP"))
        self.is_connect_1.setText(_translate("Interfaces", "Shutdown"))
        self.is_up_2.setText(_translate("Interfaces", "Is UP"))
        self.is_connect_2.setText(_translate("Interfaces", "Shutdown"))
        self.is_up_3.setText(_translate("Interfaces", "Is UP"))
        self.is_connect_3.setText(_translate("Interfaces", "Shutdown"))
        self.is_up_4.setText(_translate("Interfaces", "Is UP"))
        self.is_connect_4.setText(_translate("Interfaces", "Shutdown"))

        self.is_up_1_data.setText(_translate("Interfaces", "OFF"))
        self.is_connect_1_data.setText(_translate("Interfaces", "OFF"))
        self.is_up_2_data.setText(_translate("Interfaces", "OFF"))
        self.is_connect_2_data.setText(_translate("Interfaces", "OFF"))
        self.is_up_3_data.setText(_translate("Interfaces", "OFF"))
        self.is_connect_3_data.setText(_translate("Interfaces", "OFF"))
        self.is_up_4_data.setText(_translate("Interfaces", "OFF"))
        self.is_connect_4_data.setText(_translate("Interfaces", "OFF"))
        self.InterfaceName1.setText(_translate("Interfaces", "Interface 0/0/0"))
        self.label_3.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName2.setText(_translate("Interfaces", "Interface 0/0/1"))
        self.label_6.setText(_translate("Interfaces", "IP"))
        self.label_7.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName3.setText(_translate("Interfaces", "Interface 0/0/2"))
        self.label_10.setText(_translate("Interfaces", "IP"))
        self.label_11.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName4.setText(_translate("Interfaces", "Interface 0/0/3"))
        self.label_14.setText(_translate("Interfaces", "IP"))
        self.label_15.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName5.setText(_translate("Interfaces", "Interface 0/0/4"))
        self.label_18.setText(_translate("Interfaces", "IP"))
        self.label_19.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName6.setText(_translate("Interfaces", "Interface 0/0/5"))
        self.label_22.setText(_translate("Interfaces", "IP"))
        self.label_23.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName7.setText(_translate("Interfaces", "Interface 0/0/6"))
        self.label_26.setText(_translate("Interfaces", "IP"))
        self.label_27.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceName8.setText(_translate("Interfaces", "Interface 0/0/7"))
        self.label_30.setText(_translate("Interfaces", "IP"))
        self.label_31.setText(_translate("Interfaces", "Subnet Mask"))
        self.InterfaceMask0.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP0.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask1.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP1.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP2.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask2.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP3.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask3.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP4.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask4.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP5.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask5.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP6.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask6.setText(_translate("Interfaces", "No data"))
        self.InterfaceIP7.setText(_translate("Interfaces", "No data"))
        self.InterfaceMask7.setText(_translate("Interfaces", "No data"))
        self.IntEdit0.setText(_translate("Interfaces", "Edit"))
        self.IntEdit1.setText(_translate("Interfaces", "Edit"))
        self.IntEdit3.setText(_translate("Interfaces", "Edit"))
        self.IntEdit2.setText(_translate("Interfaces", "Edit"))
        self.IntEdit4.setText(_translate("Interfaces", "Edit"))
        self.IntEdit5.setText(_translate("Interfaces", "Edit"))
        self.IntEdit6.setText(_translate("Interfaces", "Edit"))
        self.IntEdit7.setText(_translate("Interfaces", "Edit"))
        self.IntExit.setText(_translate("Interfaces", "Back"))
        self.reloadButton.setText(_translate("Interfaces", "Reload"))



