# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StaticRoutingCreatorFirewall.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import ipaddress
from PyQt5 import QtCore, QtGui, QtWidgets

from Error import Ui_Error


class Ui_StaticRoutingCreatorFirewall(object):
    StaticRoutingCreatorFirewall = None
    dev = None
    row = None
    name = None
    data = None
    firewall = None

    def reload(self):
        _translate = QtCore.QCoreApplication.translate

        self.NetworkEdit.setText(_translate("StaticRoutingCreatorFirewall", self.data[self.row][0]))
        self.NextHopEdit.setText(_translate("StaticRoutingCreatorFirewall", self.data[self.row][1]))

    def valid(self):
        try:
            ipaddress.ip_network(self.NetworkEdit.text())
            ipaddress.ip_address(self.NextHopEdit.text())
            return True
        except Exception as e:
            self.openErrorWindow(e)
            return False

    def commit(self):
        try:
            if self.valid():
                if self.row is not None:
                    if self.NetworkEdit == self.data[self.row][0] and self.NextHopEdit == self.data[self.row][1]:
                        self.exit()
                    else:
                        self.firewall.load_merge_candidate(
                            config="delete routing-options static route " + self.data[self.row][0] + " next-hop " +
                                   self.data[self.row][1])
                self.firewall.load_merge_candidate(
                    config="set routing-options static route " + self.NetworkEdit.text() + " next-hop " + self.NextHopEdit.text())
                self.firewall.commit_config()
            self.exit()
        except Exception as e:
            self.openErrorWindow(e)

    def exit(self):
        self.PrevWindow.show()
        self.centralwidget.window().close()

    def openErrorWindow(self, txt):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Error()
        self.ui.setupUi(self.window, self.StaticRoutingCreatorFirewall)
        self.ui.reload(txt)
        self.window.show()

    def setupUi(self, StaticRoutingCreatorFirewall, PrevWindow):
        self.PrevWindow = PrevWindow
        self.PrevWindow.hide()
        self.StaticRoutingCreatorFirewall = StaticRoutingCreatorFirewall

        StaticRoutingCreatorFirewall.setObjectName("StaticRoutingCreatorFirewall")
        StaticRoutingCreatorFirewall.resize(350, 220)
        StaticRoutingCreatorFirewall.setMinimumSize(QtCore.QSize(350, 220))
        StaticRoutingCreatorFirewall.setMaximumSize(QtCore.QSize(350, 220))
        self.centralwidget = QtWidgets.QWidget(StaticRoutingCreatorFirewall)
        self.centralwidget.setObjectName("centralwidget")
        self.NetworkLabel = QtWidgets.QLabel(self.centralwidget)
        self.NetworkLabel.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.NetworkLabel.setObjectName("NetworkLabel")
        self.NetworkEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NetworkEdit.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.NetworkEdit.setObjectName("NetworkEdit")
        """ self.MaskEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MaskEdit.setGeometry(QtCore.QRect(20, 90, 171, 20))
        self.MaskEdit.setText("")
        self.MaskEdit.setObjectName("MaskEdit")
        self.MaskLabel = QtWidgets.QLabel(self.centralwidget)
        self.MaskLabel.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.MaskLabel.setObjectName("MaskLabel")"""
        self.NextHopEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NextHopEdit.setGeometry(QtCore.QRect(20, 90, 171, 20))
        self.NextHopEdit.setText("")
        self.NextHopEdit.setObjectName("NextHopEdit")
        self.nextHopLabel = QtWidgets.QLabel(self.centralwidget)
        self.nextHopLabel.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.nextHopLabel.setObjectName("nextHopLabel")
        self.commitBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.commit())
        self.commitBtn.setGeometry(QtCore.QRect(230, 110, 75, 23))
        self.commitBtn.setObjectName("commitBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.exit())
        self.exitBtn.setGeometry(QtCore.QRect(230, 80, 75, 23))
        self.exitBtn.setObjectName("exitBtn")
        StaticRoutingCreatorFirewall.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaticRoutingCreatorFirewall)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        StaticRoutingCreatorFirewall.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaticRoutingCreatorFirewall)
        self.statusbar.setObjectName("statusbar")
        StaticRoutingCreatorFirewall.setStatusBar(self.statusbar)

        self.retranslateUi(StaticRoutingCreatorFirewall)
        QtCore.QMetaObject.connectSlotsByName(StaticRoutingCreatorFirewall)

    def retranslateUi(self, StaticRoutingCreatorFirewall):
        _translate = QtCore.QCoreApplication.translate
        StaticRoutingCreatorFirewall.setWindowTitle(_translate("StaticRoutingCreatorFirewall", "PyNet"))
        self.NetworkLabel.setText(_translate("StaticRoutingCreatorFirewall", "Network"))
        self.nextHopLabel.setText(_translate("StaticRoutingCreatorFirewall", "Next-Hop"))
        self.commitBtn.setText(_translate("StaticRoutingCreatorFirewall", "Commit"))
        self.exitBtn.setText(_translate("StaticRoutingCreatorFirewall", "Exit"))
