# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserCreator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from Error import Ui_Error


class Ui_UserCreator:
    UsersCreator = None
    PrevWindow = None
    vendor = None  # 0-Juniper 1-Cisco
    dev = None
    data = []
    row = None
    add = False

    def reload(self):
        if self.vendor == 0:
            self.PasswordEdit.hide()
            self.passwordLabel.hide()

        if not self.add:
            _translate = QtCore.QCoreApplication.translate
            self.NameEdit.setText(_translate("UserCreator", self.data[self.row][0]))
            if self.data[self.row][1] == 0:
                self.click(1)
            if self.data[self.row][1] == 1:
                self.click(3)
            if self.data[self.row][1] == 15:
                self.click(2)


    def click(self, idx):
        if self.readonlyBtn.isChecked():
            self.readonlyBtn.nextCheckState()
        if self.UnauthorizedBtn.isChecked():
            self.UnauthorizedBtn.nextCheckState()
        if self.SuperuserBtn.isChecked():
            self.SuperuserBtn.nextCheckState()
        if idx == 1:
            self.UnauthorizedBtn.nextCheckState()
        if idx == 2:
            self.SuperuserBtn.nextCheckState()
        if idx == 3:
            self.readonlyBtn.nextCheckState()

    def openErrorWindow(self, txt):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Error()
        self.ui.setupUi(self.window, self.UsersCreator)
        self.ui.reload(txt)
        self.window.show()

    def commit(self):
        try:
            if self.vendor == 0:
                if not self.add:
                    self.dev.load_merge_candidate(
                        config="delete system login user " + self.data[self.row][0])
                if self.readonlyBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="set system login user " + self.NameEdit.text() + " class read-only")
                if self.UnauthorizedBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="set system login user " + self.NameEdit.text() + " class unauthorized")
                if self.SuperuserBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="set system login user " + self.NameEdit.text() + " class super-user")

            if self.vendor == 1:
                if not self.add:
                    self.dev.load_merge_candidate(
                        config="no username " + self.data[self.row][0] + "\ny\n")
                if self.readonlyBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="username " + self.NameEdit.text() + " privilege 1 password 0 " + self.PasswordEdit.text())
                if self.UnauthorizedBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="username " + self.NameEdit.text() + " privilege 0 password 0 " + self.PasswordEdit.text())
                if self.SuperuserBtn.isChecked():
                    self.dev.load_merge_candidate(
                        config="username " + self.NameEdit.text() + " privilege 15 password 0 " + self.PasswordEdit.text())
            self.dev.commit_config()
        except Exception as e:
            self.openErrorWindow(e)

    def exit(self):
        self.PrevWindow.show()
        self.centralwidget.window().close()

    def setupUi(self, UserCreator, PrevWindow):
        self.PrevWindow = PrevWindow
        self.PrevWindow.hide()
        self.UserCreator = UserCreator

        UserCreator.setObjectName("UserCreator")
        UserCreator.resize(350, 220)
        UserCreator.setMinimumSize(QtCore.QSize(350, 220))
        UserCreator.setMaximumSize(QtCore.QSize(350, 220))
        self.centralwidget = QtWidgets.QWidget(UserCreator)
        self.centralwidget.setObjectName("centralwidget")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.NameLabel.setObjectName("NameLabel")
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.NameEdit.setObjectName("NameEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordEdit.setGeometry(QtCore.QRect(20, 140, 171, 20))
        self.PasswordEdit.setText("*********")
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.commitBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.commit())
        self.commitBtn.setGeometry(QtCore.QRect(230, 110, 75, 23))
        self.commitBtn.setObjectName("commitBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.exit())
        self.exitBtn.setGeometry(QtCore.QRect(230, 80, 75, 23))
        self.exitBtn.setObjectName("exitBtn")
        self.UnauthorizedBtn = QtWidgets.QRadioButton(self.centralwidget, clicked=lambda: self.click(1))
        self.UnauthorizedBtn.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.UnauthorizedBtn.setObjectName("UnauthorizedBtn")
        self.SuperuserBtn = QtWidgets.QRadioButton(self.centralwidget, clicked=lambda: self.click(2))
        self.SuperuserBtn.setGeometry(QtCore.QRect(110, 70, 82, 17))
        self.SuperuserBtn.setObjectName("SuperuserBtn")
        self.readonlyBtn = QtWidgets.QRadioButton(self.centralwidget, clicked=lambda: self.click(3))
        self.readonlyBtn.setGeometry(QtCore.QRect(20, 90, 82, 17))
        self.readonlyBtn.setObjectName("readonlyBtn")
        UserCreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UserCreator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        UserCreator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UserCreator)
        self.statusbar.setObjectName("statusbar")
        UserCreator.setStatusBar(self.statusbar)

        self.retranslateUi(UserCreator)
        QtCore.QMetaObject.connectSlotsByName(UserCreator)

    def retranslateUi(self, UserCreator):
        _translate = QtCore.QCoreApplication.translate
        UserCreator.setWindowTitle(_translate("UserCreator", "PyNet"))
        self.NameLabel.setText(_translate("UserCreator", "Name"))
        self.passwordLabel.setText(_translate("UserCreator", "Password"))
        self.commitBtn.setText(_translate("UserCreator", "Commit"))
        self.exitBtn.setText(_translate("UserCreator", "Exit"))
        self.UnauthorizedBtn.setText(_translate("UserCreator", "Unauthorized"))
        self.SuperuserBtn.setText(_translate("UserCreator", "super-user"))
        self.readonlyBtn.setText(_translate("UserCreator", "read-only"))
